# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
Bundler.require
require_all './spec/support/**/*.rb'
require_all './app/**/*.rb'

require 'rack/test'

ENV['RACK_ENV'] = 'test'

DataMapper::Logger.new($stdout, :error)
DataMapper.setup(:default, "sqlite:///tmp/ad_test.db")
DataMapper.auto_upgrade!

RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
#  config.order = 'random'
end

def app
  Server
end


def get_v2(path, attributes=nil)
  header("Accept-Version", "v2")
  get path, attributes
end

def post_v2(path, attributes=nil)
  header("Accept-Version", "v2")
  post path, attributes
end

def get_v1(path, attributes=nil)
  header("Accept-Version", "v1")
  get path, attributes
end

def post_v1(path, attributes=nil)
  header("Accept-Version", "v1")
  post path, attributes
end
